### ISSUE TITLE
Using flag `--dates` with integers doesn't works

### ISSUE THREAD

**Issue by jgmanzanas** [roobre/pydoodle#4]
Flag `--dates` with integer returns an exception expecting a date instead an integer.

![image](https://user-images.githubusercontent.com/22660449/110969398-ee1a6500-8358-11eb-91d5-f7e08e46ad63.png)

**Comment by nadiamoe** [comment]
Works for me :(

```
> $ python doodle.py 'Anime something' --dates :+2 --after 16 --before 23
https://doodle.com/poll/t3q7e7yb7awrpxii
```

**Comment by jgmanzanas** [comment]
(On master/latest) Not for me, maybe something related to Windows?
```python
PS E:\User\Documents\personal_coding\pydoodle> python doodle.py 'Anime something' --dates :+2 --after 16 --before 23
Traceback (most recent call last):
  File "doodle.py", line 187, in <module>
    main()
  File "doodle.py", line 34, in main
    dates = dates_from_arg(args)
  File "doodle.py", line 120, in dates_from_arg
    start, _ = derelativize_date(parts[0])
  File "doodle.py", line 71, in derelativize_date
    return datetime.strptime(datestr, '%Y-%m-%d'), relative
  File "C:\Program Files\Python37\lib\_strptime.py", line 577, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "C:\Program Files\Python37\lib\_strptime.py", line 359, in _strptime
    (data_string, format))
ValueError: time data '' does not match format **'%Y-%m-%d'**
```

**Comment by nadiamoe** [comment]
Can you double-check you're running this on `master` (https://github.com/roobre/pydoodle/commit/eefecd0bb455f45880a31d239c3623ab7c2fe7da)?

I cannot find this line (from the error message):
`return datetime.strptime(datestr, '%Y-%m-%d'), relative`
In the code. The line should be:
https://github.com/roobre/pydoodle/blob/eefecd0bb455f45880a31d239c3623ab7c2fe7da/doodle.py#L72

**Comment by jgmanzanas** [comment]
That was on my branch, my bad
